version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo

  app:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes:
      - .:/usr/src/clean-node-api
    ports:
      - "5050:5050"
    networks:
      - mongo
    depends_on:
      - mongo

networks:
  mongo:
    driver: bridge
